version: '3'

services:
  app:
    container_name: my_app
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: my_mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
    volumes:
      - ./dataset:/app/dataset
      - ./resources:/app/resources
    devices:
      - /dev/video0:/dev/video0  # Mapea el dispositivo de cámara del host al contenedor
    privileged: true  # Opción que da acceso a dispositivos y funcionalidades especiales (menos seguro)
    depends_on:
      - db
    networks:
      - my-network

  db:
    container_name: my_mysql_db
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
    volumes:
      - db_data:/var/lib/mysql
      - ./flask_db.sql:/docker-entrypoint-initdb.d/flask_db.sql
    command: --init-file /docker-entrypoint-initdb.d/flask_db.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
